# Generated by Django 3.1.3 on 2021-01-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordersum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderSum',
        ),
    ]
