# Generated by Django 3.1.3 on 2021-01-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_ordersum'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orderitem')),
            ],
        ),
    ]
