# Generated by Django 3.1.3 on 2021-01-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_ordersum'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='data', to='core.orderitem'),
            preserve_default='True',
        ),
    ]
