# Generated by Django 3.1.3 on 2021-01-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210106_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='item',
        ),
    ]
