# Generated by Django 3.1.3 on 2021-01-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
