# Generated by Django 3.1.3 on 2021-01-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='order',
            field=models.IntegerField(),
        ),
    ]
