# Generated by Django 3.1.3 on 2021-01-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210107_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='order',
            field=models.CharField(max_length=30),
        ),
    ]
