# Generated by Django 3.1.3 on 2021-01-09 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='requested_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
